### ISSUE TITLE
앱서버 구현

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_A#21]
앱서버 구현

**Comment by lunar999** [comment]
앱서버 구현사항을 여기에 간략하게 적으면 더 좋을듯해요 아니면 github  페이지르 연결하셔도 되요

**Comment by parkdaye** [comment]
## 개요
* [Randommenu_Server](https://github.com/parkdaye/RandomMenu_server)
* [api 명세서](http://ec2-54-180-49-154.ap-northeast-2.compute.amazonaws.com:8080/swagger-ui.html#/)
## 구현사항
* 로그인, 인증 회원가입
* 상점 및 메뉴정보 변경사항 저장, 불러오기
* 내 현재좌표 주위에 있는 상점좌표정보와 메뉴정보 불러오기
## 사용도구
* Spring boot
* Maven
* Tomcat
* MySql
* Amazon ec2, rds, s3
* intelliJ
