### ISSUE TITLE
[bug] 스와이프 화면 진입후 지도화면 재진입시 지도가 까맣게 나오는 현상 

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_A#68]
스와이프 화면 진입후 지도화면 재진입시 지도가 까맣게 나오고 있는데 이부분 수정 필요해 보입니다

**Comment by nusurprise** [comment]
버그 확인했습니다, 생명주기에 따라 MapView를 addView, removeView하는 방식으로 바꾸겠습니다
