### ISSUE TITLE
[bug] 최초 가입후 정보 입력 할수 없음

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_A#69]
싸장님이 가입하고나서 인증번호 인증후 나오는 첫화면에서 아무것도 할 수 없음

편집? 메뉴도 안나오는듯 한데 확인해보세요

![kakaotalk_image_2019-02-19-13-25-27](https://user-images.githubusercontent.com/2384779/52990080-d4441780-3449-11e9-920c-2a6ceeb4597f.jpeg)

**Comment by ch-Yoon** [comment]
확인해보니, 업주 flag를 false로 넘겨주는 오타 발견했습니다. 수정하겠습니다.

**Comment by ch-Yoon** [comment]
fbb307512c77b49a2bb8eebe93ac36c99faa4fba

오타 에러 해결 후 commit했습니다

**Comment by lunar999** [comment]
해당 코드는 확인했습니다
develop에 merge됐으면 이슈 close해주세요
