### ISSUE TITLE
[UX개선] 검색한 지도영역에 등록된 가게가 없는 경우

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_A#73]
1. 검색한 지도영역에 등록된 가게(메뉴)가 없는 경우 (신사동 검색함)
2. 메뉴 랜덤 스와이프 시작 버튼을 눌렀을때 
3. 요청된 결과가 없습니다 라는 토스트 메시지가 나오면서  스와이프 엑티비티로 이동
4. 다시 이전화면으로 돌아옴(화면 에니메이션 나옴)
이부분이 좀 많이 어색해보세요. 아예 못가게 하거나, 버튼 비활성화를 하는건 어떨까요?
이미 서버에서 현재 근처에 몇개의 아이템이 있는지는 이화면에서 알고 있을꺼 같은데요

**Comment by nusurprise** [comment]
'스와이프 가능한 메뉴가 없습니다' 토스트 메세지를 출력하고
 다음 화면으로 넘어가지 못 하도록 변경했습니다
