### ISSUE TITLE
[bug] 지도화면내 마커가 깨지는 현상

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_A#74]
스와이프 선택후에 지도 화면으로 돌아온후 까맣게 된 화면 이후에 다시 처음화면(시작)으로 갔다가 다시 지도화면으로 오면 마커가 깨지고 그리고 주소는 왜 자꾸 이전 검색했던 위치가 남아서 기본으로 설정되어 있을까요? 뭔가 초기화가 되거나 아예 현재 위치 중심으로 나오는게 더 좋지 않을까요? 

<img width="394" alt="2019-02-20 1 10 46" src="https://user-images.githubusercontent.com/2384779/53029512-62e98080-34ac-11e9-8de6-c750d36e2c4f.png">

**Comment by nusurprise** [comment]
1. 이전 위치와 줌레벨을 저장하여 이전 위치로 복귀하도록 변경했습니다
2. marker문제는 이미지 해상도를 변경해서 적용해보겠습니다
